'NoneType' object has no attribute 'update'
Traceback (most recent call last):  File './text_to_speech/mywords_library.py', line 62, in google_cvs_prepareAttributeError: 'NoneType' object has no attribute 'update'
csv data upload failed. please check syslog table for more details
'NoneType' object has no attribute 'update'
Traceback (most recent call last):  File './text_to_speech/mywords_library.py', line 62, in google_cvs_prepareAttributeError: 'NoneType' object has no attribute 'update'
csv data upload failed. please check syslog table for more details
'NoneType' object has no attribute 'update'
Traceback (most recent call last):  File './text_to_speech/mywords_library.py', line 62, in google_cvs_prepareAttributeError: 'NoneType' object has no attribute 'update'
csv data upload failed. please check syslog table for more details
'NoneType' object has no attribute 'update'
Traceback (most recent call last):  File './text_to_speech/mywords_library.py', line 62, in google_cvs_prepareAttributeError: 'NoneType' object has no attribute 'update'
'NoneType' object has no attribute 'update'
Traceback (most recent call last):  File './text_to_speech/mywords_library.py', line 62, in google_cvs_prepareAttributeError: 'NoneType' object has no attribute 'update'
'NoneType' object has no attribute 'update'
Traceback (most recent call last):  File './text_to_speech/mywords_library.py', line 63, in google_cvs_prepareAttributeError: 'NoneType' object has no attribute 'update'
'NoneType' object has no attribute 'update'
Traceback (most recent call last):  File './text_to_speech/mywords_library.py', line 63, in google_cvs_prepareAttributeError: 'NoneType' object has no attribute 'update'
'NoneType' object has no attribute 'update'
Traceback (most recent call last):  File './text_to_speech/mywords_library.py', line 64, in google_cvs_prepareAttributeError: 'NoneType' object has no attribute 'update'
module 'csv' has no attribute 'Reader'
Traceback (most recent call last):  File './text_to_speech/mywords_library.py', line 60, in google_cvs_prepareAttributeError: module 'csv' has no attribute 'Reader'
module 'csv' has no attribute 'Reader'
Traceback (most recent call last):  File './text_to_speech/mywords_library.py', line 60, in google_cvs_prepareAttributeError: module 'csv' has no attribute 'Reader'
 expected at least 1 arguments, got 0
Traceback (most recent call last):  File './text_to_speech/mywords_library.py', line 60, in google_cvs_prepareTypeError:  expected at least 1 arguments, got 0
 expected at least 1 arguments, got 0
Traceback (most recent call last):  File './text_to_speech/mywords_library.py', line 60, in google_cvs_prepareTypeError:  expected at least 1 arguments, got 0
 expected at least 1 arguments, got 0
Traceback (most recent call last):  File './text_to_speech/mywords_library.py', line 60, in google_cvs_prepareTypeError:  expected at least 1 arguments, got 0
'NoneType' object is not subscriptable
Traceback (most recent call last):  File './text_to_speech/mywords_library.py', line 83, in insert_dataTypeError: 'NoneType' object is not subscriptable
